### ISSUE TITLE
This list does not appear to be in sync with official BadActorList

### ISSUE THREAD

**Issue by blocktrades** [gryter/plentyofphish#2]
I'm not sure if this list is somehow separate that it does not want to mirror the official BadActorList, but I noticed there are entries here that are not reflected in your list:
https://github.com/steemit/condenser/blob/master/src/app/utils/BadActorList.js

**Comment by gryter** [comment]
It is not meant to be in sync with BadActorList.js 

The BadActorList.js mostly has deliberate misspellings of accounts and other scammers.  This list is phishing hacker accounts and phishing victim accounts under hacker control.
